package com.sample;
import java.util.ArrayList;
import javax.swing.JOptionPane;

declare Question
	questionText : String
	possibleAnswersList : ArrayList
	answer : String
end

declare FinalChoice
	choice : String
end

rule "init"
	when 
	then
		ArrayList<String> possibleAnswersList = new ArrayList<>();
		possibleAnswersList.add("Book");
		possibleAnswersList.add("Infographic");
		possibleAnswersList.add("Logo");
		possibleAnswersList.add("Newspaper");
		insert(new Question("What do you need a typeface for?",possibleAnswersList,null));
end
 
rule "show-question-get-answer"
	when
		question: Question(getAnswer() == null)
    then
    	showQuestion(question);    	
		update(question);
end

rule "101"
	when 
		Question(getQuestionText() == "What do you need a typeface for?", getAnswer() == "Book")
	then
		ArrayList<String> possibleAnswersList = new ArrayList<>();
		possibleAnswersList.add("Yes");
		possibleAnswersList.add("No");
		insert(new Question("Are you completely in doubt?",possibleAnswersList,null));
end

rule "102"
	when 
		Question(getQuestionText() == "Are you completely in doubt?", getAnswer() == "Yes")
	then
		showFinalChoice("Perfect typeface for you: Calson");
end

function void showQuestion(Question question){
	question.setAnswer(GuiHandler.showQuestion(question.getQuestionText(), question.getPossibleAnswersList()));
}

function void showFinalChoice(String choiceText){
	GuiHandler.showFinalChoice(choiceText);
}

